name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test3-test
      id: test3-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
        max_score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST3_RESULTS: "${{steps.test3-test.outputs.result}}"
      with:
        runners: test3-test
